/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Space.def

namespace KBEngine
{

class EntityBaseEntityCall_SpaceBase : public EntityCall
{
public:

	EntityBaseEntityCall_SpaceBase(int32 eid, const KBString& ename);

	virtual ~EntityBaseEntityCall_SpaceBase();
};

class EntityCellEntityCall_SpaceBase : public EntityCall
{
public:

	EntityCellEntityCall_SpaceBase(int32 eid, const KBString& ename);

	virtual ~EntityCellEntityCall_SpaceBase();
};

}