/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Gate.def

namespace KBEngine
{

class EntityBaseEntityCall_GateBase : public EntityCall
{
public:

	EntityBaseEntityCall_GateBase(int32 eid, const KBString& ename);

	virtual ~EntityBaseEntityCall_GateBase();
};

class EntityCellEntityCall_GateBase : public EntityCall
{
public:

	EntityCellEntityCall_GateBase(int32 eid, const KBString& ename);

	virtual ~EntityCellEntityCall_GateBase();
};

}