/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"

namespace KBEngine
{

// defined in */res/server/server_errors.xml

class ServerErrorDescrs
{
public:
	ServerErrorDescrs():
	serverErrs_()
	{
		{
			FKServerErr e;
			e.id = 0;
			e.name = KBTEXT("SUCCESS");
			e.descr = KBTEXT("成功。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 1;
			e.name = KBTEXT("SERVER_ERR_SRV_NO_READY");
			e.descr = KBTEXT("服务器没有准备好。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 2;
			e.name = KBTEXT("SERVER_ERR_SRV_OVERLOAD");
			e.descr = KBTEXT("服务器负载过重。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 3;
			e.name = KBTEXT("SERVER_ERR_ILLEGAL_LOGIN");
			e.descr = KBTEXT("非法登录。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 4;
			e.name = KBTEXT("SERVER_ERR_NAME_PASSWORD");
			e.descr = KBTEXT("用户名或者密码不正确。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 5;
			e.name = KBTEXT("SERVER_ERR_NAME");
			e.descr = KBTEXT("用户名不正确。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 6;
			e.name = KBTEXT("SERVER_ERR_PASSWORD");
			e.descr = KBTEXT("密码不正确。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 7;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_CREATE_FAILED");
			e.descr = KBTEXT("创建账号失败。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 8;
			e.name = KBTEXT("SERVER_ERR_BUSY");
			e.descr = KBTEXT("操作过于繁忙(例如：在服务器前一次请求未执行完毕的情况下连续N次创建账号)。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 9;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_LOGIN_ANOTHER");
			e.descr = KBTEXT("当前账号在另一处登录了。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 10;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_IS_ONLINE");
			e.descr = KBTEXT("账号已登陆。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 11;
			e.name = KBTEXT("SERVER_ERR_PROXY_DESTROYED");
			e.descr = KBTEXT("与客户端关联的proxy在服务器上已经销毁。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 12;
			e.name = KBTEXT("SERVER_ERR_ENTITYDEFS_NOT_MATCH");
			e.descr = KBTEXT("EntityDefs不匹配。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 13;
			e.name = KBTEXT("SERVER_ERR_SERVER_IN_SHUTTINGDOWN");
			e.descr = KBTEXT("服务器正在关闭中。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 14;
			e.name = KBTEXT("SERVER_ERR_NAME_MAIL");
			e.descr = KBTEXT("Email地址错误。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 15;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_LOCK");
			e.descr = KBTEXT("账号被冻结。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 16;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_DEADLINE");
			e.descr = KBTEXT("账号已过期。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 17;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_NOT_ACTIVATED");
			e.descr = KBTEXT("账号未激活。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 18;
			e.name = KBTEXT("SERVER_ERR_VERSION_NOT_MATCH");
			e.descr = KBTEXT("与服务端的版本不匹配。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 19;
			e.name = KBTEXT("SERVER_ERR_OP_FAILED");
			e.descr = KBTEXT("操作失败。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 20;
			e.name = KBTEXT("SERVER_ERR_SRV_STARTING");
			e.descr = KBTEXT("服务器正在启动中。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 21;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_REGISTER_NOT_AVAILABLE");
			e.descr = KBTEXT("未开放账号注册功能。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 22;
			e.name = KBTEXT("SERVER_ERR_CANNOT_USE_MAIL");
			e.descr = KBTEXT("不能使用email地址。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 23;
			e.name = KBTEXT("SERVER_ERR_NOT_FOUND_ACCOUNT");
			e.descr = KBTEXT("找不到此账号。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 24;
			e.name = KBTEXT("SERVER_ERR_DB");
			e.descr = KBTEXT("数据库错误(请检查dbmgr日志和DB)。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 25;
			e.name = KBTEXT("SERVER_ERR_USER1");
			e.descr = KBTEXT("用户自定义错误码1。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 26;
			e.name = KBTEXT("SERVER_ERR_USER2");
			e.descr = KBTEXT("用户自定义错误码2。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 27;
			e.name = KBTEXT("SERVER_ERR_USER3");
			e.descr = KBTEXT("用户自定义错误码3。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 28;
			e.name = KBTEXT("SERVER_ERR_USER4");
			e.descr = KBTEXT("用户自定义错误码4。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 29;
			e.name = KBTEXT("SERVER_ERR_USER5");
			e.descr = KBTEXT("用户自定义错误码5。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 30;
			e.name = KBTEXT("SERVER_ERR_USER6");
			e.descr = KBTEXT("用户自定义错误码6。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 31;
			e.name = KBTEXT("SERVER_ERR_USER7");
			e.descr = KBTEXT("用户自定义错误码7。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 32;
			e.name = KBTEXT("SERVER_ERR_USER8");
			e.descr = KBTEXT("用户自定义错误码8。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 33;
			e.name = KBTEXT("SERVER_ERR_USER9");
			e.descr = KBTEXT("用户自定义错误码9。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 34;
			e.name = KBTEXT("SERVER_ERR_USER10");
			e.descr = KBTEXT("用户自定义错误码10。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 35;
			e.name = KBTEXT("SERVER_ERR_LOCAL_PROCESSING");
			e.descr = KBTEXT("本地处理，通常为某件事情不由第三方处理而是由KBE服务器处理。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 36;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_RESET_PASSWORD_NOT_AVAILABLE");
			e.descr = KBTEXT("未开放账号重置密码功能。");

			serverErrs_.Add(e.id, e);
		}

		{
			FKServerErr e;
			e.id = 37;
			e.name = KBTEXT("SERVER_ERR_ACCOUNT_LOGIN_ANOTHER_SERVER");
			e.descr = KBTEXT("当前账号在其他服务器登陆了。");

			serverErrs_.Add(e.id, e);
		}

	}

	void Clear()
	{
		serverErrs_.Clear();
	}

	KBString ServerErrStr(uint16 id)
	{
		FKServerErr e = serverErrs_.FindRef(id);
		return KBString::Printf(KBTEXT("%s[%s]"), e.name.c_str(), e.descr.c_str());
	}

	FKServerErr ServerErr(uint16 id)
	{
		return serverErrs_.FindRef(id);
	}

	protected:
		KBMap<uint16, FKServerErr> serverErrs_;
};

}